### ISSUE TITLE
Error filtering hosts by sites

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#1093]
Cannot perform join in mongoDB: site__name

**Comment by t-gerhard** [comment]
```
Traceback (most recent call last):
  File "/code/tomato/lib/rpc/xmlrpc.py", line 256, in execute
    res = func(*args, **kwargs)
  File "/code/tomato/lib/cache.py", line 126, in __call__
    return self._cache.get(args, kwargs)
  File "/code/tomato/lib/cache.py", line 52, in get
    self.update(args, kwargs)
  File "/code/tomato/lib/cache.py", line 56, in update
    value = self._fn(*args, **kwargs) #there may be concurrent method calls here. set() will resolve this.
  File "/code/tomato/api/host.py", line 143, in host_list
    return [h.info() for h in hosts]
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 80, in _iter_results
    self._populate_cache()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 92, in _populate_cache
    self._result_cache.append(self.next())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1383, in next
    raw_doc = self._cursor.next()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1449, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1483, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/transform.py", line 61, in query
    raise InvalidQueryError(e)
InvalidQueryError: Cannot perform join in mongoDB: site__name
```
