### ISSUE TITLE
{'code': None, 'data': {'function': 'template_info', 'args': ['ryu'], 'trace': 'Traceback (most rece ...

### ISSUE THREAD

**Issue by t-gerhard** [GLab/ToMaTo#1115]
Happened on Backend

[View in Dump Manager](http://127.0.0.1:8080/dumpmanager/group/Error__864dbfaadf0ee667700c967db0da47c4)

Description:

```
{'code': None, 'data': {'function': 'template_info', 'args': ['ryu'], 'trace': 'Traceback (most recent call last):\n  File "/code/tomato/lib/rpc/xmlrpc.py", line 256, in execute\n    res = func(*args, **kwargs)\n  File "/code/tomato/api/api_helpers.py", line 25, in call\n    return fn(*args, **kwargs)\n  File "/code/tomato/api/resources.py", line 174, in template_info\n    res = _getTemplate(id)\n  File "/code/tomato/api/resources.py", line 22, in _getTemplate\n    res = Template.objects.get(id=id_)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 238, in get\n    result = queryset.next()\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1383, in next\n    raw_doc = self._cursor.next()\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1449, in _cursor\n    self._cursor_obj = self._collection.find(self._query,\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1483, in _query\n    self._mongo_query = self._query_obj.to_query(self._document)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 90, in to_query\n    query = query.accept(QueryCompilerVisitor(document))\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 155, in accept\n    return visitor.visit_query(self)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py", line 78, in visit_query\n    return transform.query(self.document, **query.query)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/transform.py", line 95, in query\n    value = field.prepare_query_value(op, value)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 443, in prepare_query_value\n    return self.to_mongo(value)\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 439, in to_mongo\n    self.error(unicode(e))\n  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 144, in error\n    raise ValidationError(message, errors=errors, field_name=field_name)\nValidationError: u\'ryu\' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string\n', 'kwargs': {}}, 'module': 'backend', 'httpcode': 500, 'message': "u'ryu' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string", 'onscreenmessage': "u'ryu' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string", 'type': 'internal'}
```

Trace:

```
/code/tomato/lib/rpc/xmlrpc.py, line 256, in execute
 res = func(*args, **kwargs)

/code/tomato/api/api_helpers.py, line 25, in call
 return fn(*args, **kwargs)

/code/tomato/api/resources.py, line 174, in template_info
 res = _getTemplate(id)

/code/tomato/api/resources.py, line 22, in _getTemplate
 res = Template.objects.get(id=id_)

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py, line 238, in get
 result = queryset.next()

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py, line 1383, in next
 raw_doc = self._cursor.next()

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py, line 1449, in _cursor
 self._cursor_obj = self._collection.find(self._query,

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py, line 1483, in _query
 self._mongo_query = self._query_obj.to_query(self._document)

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py, line 90, in to_query
 query = query.accept(QueryCompilerVisitor(document))

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py, line 155, in accept
 return visitor.visit_query(self)

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/visitor.py, line 78, in visit_query
 return transform.query(self.document, **query.query)

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/transform.py, line 95, in query
 value = field.prepare_query_value(op, value)

/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py, line 443, in prepare_query_value
 return self.to_mongo(value)

/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py, line 439, in to_mongo
 self.error(unicode(e))

/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py, line 144, in error
 raise ValidationError(message, errors=errors, field_name=field_name)
```

**Comment by t-gerhard** [comment]
Happened when calling ```template_info('ryu')``` in the cli client. This should not be dumped.
