### ISSUE TITLE
Error on host_list while runing test

### ISSUE THREAD

**Issue by swuest** [GLab/ToMaTo#1355]
I get frequently the following error while using the host_list API call on backend core:

> unknown internal error [None]: AttributeError("'NoneType' object has no attribute 'name'",)
>                    function='host_list'
>                      args=[]
>                      kwargs={}

## Stack trace:

```
Traceback (most recent call last):
  File "backend_api/topology_test.py", line 23, in setUpClass
    cls.add_templates_if_missing()
  File "backend_api/proxies.py", line 199, in add_templates_if_missing
    for host in proxy_holder.backend_core.host_list():
  File "backend_api/proxies.py", line 35, in __call__
    return self._backend_api.debug_run_internal_api_call(self._tomato_module, self._methodname, *args, **kwargs)
  File "../cli/lib/rpc/xmlrpc.py", line 337, in _call
    return call_proxy(args, kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
InternalError: unknown internal error [None]: AttributeError("'NoneType' object has no attribute 'name'",)
        function=u'host_list'
        args=[]
        trace=
                Traceback (most recent call last):
                  File "/code/service/tomato/lib/rpc/xmlrpc.py", line 256, in execute
                    res = func(*args, **kwargs)
                  File "/code/service/tomato/api/debug.py", line 47, in debug_run_internal_api_call
                    return get_tomato_inner_proxy(_tomato_module)._call(_command, args, kwargs)
                  File "/code/service/tomato/lib/sslrpc2.py", line 527, in _call
                    return self._callInternal(name, args, kwargs)
                  File "/code/service/tomato/lib/sslrpc2.py", line 496, in _callInternal
                    raise self._onError(error)
                InternalError: unknown internal error [None]: AttributeError("'NoneType' object has no attribute 'name'",)
                        function='host_list'
                        args=[]
                        kwargs={}
        kwargs={}
```

## Backend core logs:
```
Error updating host information from 131_246_112_51
Traceback (most recent call last):
  File "/code/service/tomato/host/__init__.py", line 784, in synchronizeHost
    host.synchronizeResources()
  File "/code/service/tomato/host/__init__.py", line 391, in synchronizeResources
    self.getProxy().resource_create("template", attrs)
  File "/code/service/tomato/host/__init__.py", line 55, in call
    return getattr(self._proxy, name)(*args, **kwargs)
  File "/code/service/tomato/lib/rpc/sslrpc.py", line 606, in __call__
    return self.proxy._call(self.name, args, kwargs)
  File "/code/service/tomato/lib/rpc/sslrpc.py", line 567, in _call
    return self._callInternal(name, args, kwargs)
  File "/code/service/tomato/lib/rpc/sslrpc.py", line 538, in _callInternal
    raise error
UserError: hostmanager user error [unsupported_type]: Unsupported template tech
        tech=None
Traceback (most recent call last):
  File "/code/service/tomato/lib/util.py", line 24, in call
    return fn(*args, **kwargs)
  File "/code/service/tomato/host/__init__.py", line 786, in synchronizeHost
    print >>sys.stderr, "Error updating host information from %s" % host
TypeError: __str__ returned non-string (type NoneType)
Traceback (most recent call last):
  File "/code/service/tomato/lib/util.py", line 24, in call
    return fn(*args, **kwargs)
  File "/code/service/tomato/host/__init__.py", line 807, in updateAccounting
    print >>sys.stderr, "Error updating accounting information from %s" % host
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by t-gerhard** [comment]
Does this still occur?
