### ISSUE TITLE
getpackages.py errors

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#1413]
getpackages.py has some errors:

```
Traceback (most recent call last):
  File "./getpackages.py", line 411, in uploadAndRun
    result_raw = test_topology.getArchiveResult()
  File "./getpackages.py", line 230, in getArchiveResult
    if not elinfo["rextfv_run_status"]["isAlive"]:
KeyError: 'isAlive'
```

```
Traceback (most recent call last):
  File "./getpackages.py", line 593, in <module>
    res_filename = create_archive(api, template_configs, options.target)
  File "./getpackages.py", line 525, in create_archive
    conf = qarch.getTemplateDetails(api, templ['tech'], templ['template'], templ['site'])
  File "./getpackages.py", line 470, in getTemplateDetails
    custominfo_splitted = custominfo.split(".", 2)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by dswd** [comment]
Also getpackages.py seems to retry when there is no error:

```
querying debian-8: done.  Don't worry, I'll retry.
querying debian-8: done.  Don't worry, I'll retry.
```

**Comment by t-gerhard** [comment]
this happens when rextfv_run_status is not correct. I had the same problems. It worked perfectly fine with old images.
 - KeyError 'isAlive': rextfv_run_status is missing the key.
 - NoneType object and split: getTemplateDetails returned None (because of too many retries)

**Comment by t-gerhard** [comment]
The retry without a reason is because the error message wasn't displayed in this case. I have a first fix pull request that should solve this.
